NovelFinder/Models/ErrorViewModel.cs
using System;

namespace NovelFinder.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NovelFinder/Models/Novel.cs
using System.ComponentModel.DataAnnotations;

namespace NovelFinder.Models
{
    public class Novel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string title { get; set; }
        public string rating { get; set; }
        public string numberOfRatings { get; set; }
        public string chapters { get; set; }
        public string status { get; set; }

    }
}

NovelFinder/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NovelFinder.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NovelFinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NovelFinder/Controllers/NovelsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NovelFinder.Data;
using NovelFinder.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NovelFinder.Controllers
{
    public class NovelsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public NovelsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.Novels.ToList());
        }

        [HttpGet]
        public IActionResult RefreshNovels()
        {
            return View();
        }


        [HttpPost]
        public IActionResult LoadDataFromJson()
        {
            
            List<Novel> novels = new List<Novel>();
            using (StreamReader r = new StreamReader("LightNovelPubNovels.txt"))
            {
                string json = r.ReadToEnd();
                novels = JsonConvert.DeserializeObject<List<Novel>>(json);
            }
            foreach(var novel in novels)
            {
                _db.Add(novel);
                _db.SaveChanges();
            }
           
            
            return Redirect("Index");
        }
    }
}

NovelFinder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NovelFinder/Views/Novels/Index.cshtml
@model IEnumerable<NovelFinder.Models.Novel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.rating)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.numberOfRatings)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.chapters)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rating)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.numberOfRatings)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.chapters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

NovelFinder/Views/Novels/RefreshNovels.cshtml
<br />
<h2 class="text-info">Refresh All Novels From Json File</h2>
<form asp-action="LoadDataFromJson">
<input type="submit" value="Refresh" class="btn btn-primary form-control" />
</form>

NovelFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NovelFinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NovelFinder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Novels" asp-action="Index">Novels</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NovelFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>